<?php

return array(
    array("type" => "text", "content"=> "Pages", "permissions" => ["dashboard_consult", "desks_consult", "wilayas_consult"]),
    array(
        "type" => "link",
        "content" => "Dashboard",
        "permissions" => "dashboard_consult",
        "section" => "dashboard",
        "route" => "dashboard",
        "icon" => array("type" => "font-awsome", "content" => "chart-pie"),
    ),
    array("type" => "text", "content"=> "Général", "permissions" => ["stock_consult", "inbounds_consult", "outbounds_consult", "costs_consult"]),
    array(
        "type" => "link",
        "content" => "Stock",
        "permissions" => "stock_consult",
        "section" => "stock",
        "route" => "stock",
        "icon" => array("type" => "font-awsome", "content" => "boxes"),
    ),
    array(
        "type" => "link",
        "content" => "Entrées",
        "permissions" => "inbounds_consult",
        "section" => "inbounds",
        "route" => "inbounds",
        "icon" => array("type" => "font-awsome", "content" => "sign-in-alt"),
    ),
    array(
        "type" => "link",
        "content" => "Sorties",
        "permissions" => "outbounds_consult",
        "section" => "outbounds",
        "route" => "outbounds",
        "icon" => array("type" => "font-awsome", "content" => "sign-out-alt"),
    ),
    array(
        "type" => "link",
        "content" => "Coûts",
        "permissions" => "costs_consult",
        "section" => "costs",
        "route" => "costs",
        "icon" => array("type" => "font-awsome", "content" => "calculator"),
    ),
    array(
        "type" => "link",
        "content" => "Registre des Entrées",
        "permissions" => "inboundsRegister_consult",
        "section" => "inboundsRegister",
        "route" => "inboundsRegister",
        "icon" => array("type" => "font-awsome", "content" => "sign-in-alt"),
    ),
    array(
        "type" => "link",
        "content" => "Registre des Sorties",
        "permissions" => "outboundsRegister_consult",
        "section" => "outboundsRegister",
        "route" => "outboundsRegister",
        "icon" => array("type" => "font-awsome", "content" => "sign-out-alt"),
    ),
    array("type" => "text", "content"=> "Général", "permissions" => ["stock_consult", "inbounds_consult", "outbounds_consult", "costs_consult"]),
    array(
        "type" => "link",
        "content" => "Rubriques",
        "permissions" => "rubriques_consult",
        "section" => "rubriques",
        "route" => "rubriques",
        "icon" => array("type" => "font-awsome", "content" => "align-center"),
    ),
    array(
        "type" => "link",
        "content" => "Produits",
        "permissions" => "products_consult",
        "section" => "products",
        "route" => "products",
        "icon" => array("type" => "font-awsome", "content" => "box"),
    ),
    array(
        "type" => "link",
        "content" => "Fournisseurs",
        "permissions" => "suppliers_consult",
        "section" => "suppliers",
        "route" => "suppliers",
        "icon" => array("type" => "font-awsome", "content" => "user-tie"),
    ),
    array(
        "type" => "link",
        "content" => "Services",
        "permissions" => "services_consult",
        "section" => "services",
        "route" => "services",
        "icon" => array("type" => "font-awsome", "content" => "building"),
    ),
    array("type" => "text", "content"=> "Administration", "permissions" => ["users_consult", "settings_consult"]),
    array(
        "type" => "link",
        "content" => "Users",
        "permissions" => "users_consult",
        "section" => "users",
        "route" => "users",
        "icon" => array("type" => "feather", "content" => "users"),
    ),
    array(
        "type" => "link",
        "content" => "Settings",
        "permissions" => "settings_consult",
        "section" => "settings",
        "route" => "settings",
        "icon" => array("type" => "feather", "content" => "settings"),
    ),
);